# Generated by Django 4.2.25 on 2025-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingrevision",
            name="superset_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
