# Generated by Django 4.2.25 on 2025-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="auto_approved_groups",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
