# Generated by Django 4.2.25 on 2025-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_wikiconfiguration_auto_approved_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='is_former_bot',
            field=models.BooleanField(default=False),
        ),
    ]
