# Generated by Django 4.2.25 on 2025-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_pendingpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiconfiguration',
            name='redirect_aliases',
            field=models.JSONField(blank=True, default=list, help_text="Cached redirect magic word aliases from wiki API (e.g., ['#REDIRECT', '#OHJAUS'])"),
        ),
    ]
