# Generated by Django 4.2.25 on 2025-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_editorprofile_is_former_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiconfiguration',
            name='redirect_aliases',
            field=models.JSONField(blank=True, default=list, help_text='Cached redirect magic word aliases from wiki API (i.e: https://fi.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=magicwords)'),
        ),
    ]
