# Generated by Django 4.2.25 on 2025-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_pendingrevision_render_error_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpage',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
