# Generated by Django 4.2.25 on 2025-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_pendingpage_wikidata_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="superseded_similarity_threshold",
            field=models.FloatField(
                default=0.2,
                help_text="Similarity threshold (0.0-1.0) for detecting superseded additions. Lower values are more strict. If text additions from a pending revision have similarity below this threshold in the current stable version, the revision is considered superseded and can be auto-approved.",
            ),
        ),
    ]
