# Generated by Django 4.2.25 on 2025-10-15 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_pendingpage_wikidata_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_damaging_threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES damaging model threshold (0.0-1.0). Edits with damaging probability above this will not be auto-approved. Set to 0.0 to use the global default from settings.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_damaging_threshold_living",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES damaging threshold for living person biographies (stricter). Set to 0.0 to use the global default from settings. Living people are detected via categories and Wikidata.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_goodfaith_threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES goodfaith model threshold (0.0-1.0). Edits with goodfaith probability below this will not be auto-approved. Set to 0.0 to use the global default from settings.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_goodfaith_threshold_living",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES goodfaith threshold for living person biographies (stricter). Set to 0.0 to use the global default from settings. Living people are detected via categories and Wikidata.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
