# Generated by Django 4.2.25 on 2025-10-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_add_superseded_similarity_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the review activity')),
                ('number_of_reviewers', models.IntegerField(help_text='Number of unique reviewers on this date')),
                ('number_of_reviews', models.IntegerField(help_text='Total number of reviews on this date')),
                ('number_of_pages', models.IntegerField(help_text='Number of pages reviewed on this date')),
                ('reviews_per_reviewer', models.FloatField(blank=True, help_text='Average reviews per reviewer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_activity', to='reviews.wiki')),
            ],
            options={
                'verbose_name_plural': 'Review Activity',
                'ordering': ['-date'],
                'unique_together': {('wiki', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FlaggedRevsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the statistics (monthly resolution)')),
                ('total_pages_ns0', models.IntegerField(blank=True, help_text='Total articles in main namespace', null=True)),
                ('synced_pages_ns0', models.IntegerField(blank=True, help_text='Articles reviewed to current revision', null=True)),
                ('reviewed_pages_ns0', models.IntegerField(blank=True, help_text='Articles with at least one reviewed revision', null=True)),
                ('pending_lag_average', models.FloatField(blank=True, help_text='Average time articles wait for review', null=True)),
                ('pending_changes', models.IntegerField(blank=True, help_text='Calculated as reviewedPages_ns0 - syncedPages_ns0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='reviews.wiki')),
            ],
            options={
                'verbose_name_plural': 'FlaggedRevs Statistics',
                'ordering': ['-date'],
                'unique_together': {('wiki', 'date')},
            },
        ),
    ]
