# Generated by Django 4.2.25 on 2025-10-15 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_add_superseded_similarity_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_damaging_threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Edits with damaging probability above this will not be auto-approved. ",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_damaging_threshold_living",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES damaging threshold for living person biographies (stricter). ",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_goodfaith_threshold",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Edits with goodfaith probability below this will not be auto-approved. ",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ores_goodfaith_threshold_living",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="ORES goodfaith threshold for living person biographies (stricter). ",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
