# Generated by Django 4.2.25 on 2025-10-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_add_superseded_similarity_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatisticsMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('total_records', models.IntegerField(default=0)),
                ('oldest_review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('newest_review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('wiki', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_metadata', to='reviews.wiki')),
            ],
            options={
                'verbose_name_plural': 'Review statistics metadata',
            },
        ),
        migrations.CreateModel(
            name='ReviewStatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewed_user_name', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=500)),
                ('page_id', models.BigIntegerField()),
                ('reviewed_revision_id', models.BigIntegerField()),
                ('pending_revision_id', models.BigIntegerField()),
                ('reviewed_timestamp', models.DateTimeField()),
                ('pending_timestamp', models.DateTimeField()),
                ('review_delay_days', models.IntegerField(help_text='Review delay in days')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_statistics', to='reviews.wiki')),
            ],
            options={
                'ordering': ['-reviewed_timestamp'],
                'indexes': [models.Index(fields=['wiki', 'reviewer_name'], name='reviews_rev_wiki_id_cf1e3a_idx'), models.Index(fields=['wiki', 'reviewed_user_name'], name='reviews_rev_wiki_id_2d152d_idx'), models.Index(fields=['wiki', 'reviewed_timestamp'], name='reviews_rev_wiki_id_e6065e_idx')],
                'unique_together': {('wiki', 'reviewed_revision_id')},
            },
        ),
    ]
