# Generated by Django 4.2.25 on 2025-10-16 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_wikiconfiguration_ores_damaging_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ores_damaging_score",
                    models.FloatField(
                        blank=True,
                        help_text="ORES damaging probability (0.0-1.0, higher = more likely damaging)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ores_goodfaith_score",
                    models.FloatField(
                        blank=True,
                        help_text="ORES goodfaith probability (0.0-1.0, higher = more likely good faith)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ores_fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When ORES scores were fetched from the API",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_scores",
                        to="reviews.pendingrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Scores",
                "verbose_name_plural": "Model Scores",
            },
        ),
    ]
