# Generated by Django 4.2.25 on 2025-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_modelscores"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="enabled_checks",
            field=models.JSONField(
                blank=True,
                help_text="List of check IDs to run. If empty or null, all checks will run.",
                null=True,
            ),
        ),
    ]
