# Generated by Django 4.2.25 on 2025-10-18 17:58

from django.db import migrations, models
import reviews.models.wiki_configuration


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_modelscores"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="enabled_checks",
            field=models.JSONField(
                blank=True,
                default=reviews.models.wiki_configuration._get_default_enabled_checks,
                help_text="List of check IDs to run. All checks are enabled by default.",
            ),
        ),
    ]
