# Generated by Django 4.2.25 on 2025-10-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_reviewstatisticsmetadata_reviewstatisticscache'),
        ('reviews', '0010_modelscores'),
    ]

    operations = [
    ]
