# Generated by Django 4.2.25 on 2025-10-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_merge_20251020_1128"),
        ("reviews", "0012_populate_enabled_checks"),
    ]

    operations = []
