# Generated by Django 4.2.25 on 2025-10-19 06:35

from django.db import migrations


def populate_enabled_checks(apps, schema_editor):
    """Set enabled_checks to all check IDs for existing configurations."""
    WikiConfiguration = apps.get_model("reviews", "WikiConfiguration")

    all_check_ids = [
        "manual-unapproval",
        "bot-user",
        "blocked-user",
        "auto-approved-group",
        "article-to-redirect-conversion",
        "blocking-categories",
        "new-render-errors",
        "invalid-isbn",
        "superseded-additions",
        "ores-scores",
    ]

    for config in WikiConfiguration.objects.filter(enabled_checks__isnull=True):
        config.enabled_checks = all_check_ids
        config.save(update_fields=["enabled_checks"])


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0012_update_enabled_checks_default"),
    ]

    operations = [
        migrations.RunPython(populate_enabled_checks, migrations.RunPython.noop),
    ]
