# Generated by Django 4.2.25 on 2025-10-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_reviewactivity_flaggedrevsstatistics'),
        ('reviews', '0013_merge_20251021_1821'),
    ]

    operations = [
    ]
