# Generated by Django 4.2.25 on 2025-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0013_merge_20251021_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikiconfiguration",
            name="test_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enable test mode to use specific revision IDs instead of live flaggedpages data.",
            ),
        ),
        migrations.AlterField(
            model_name="wikiconfiguration",
            name="test_revision_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of revision IDs to use when test mode is enabled.",
            ),
        ),
    ]
