# Generated by Django 4.2.25 on 2025-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_merge_20251021_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstatisticsmetadata',
            name='max_log_id',
            field=models.BigIntegerField(blank=True, help_text='Maximum log_id fetched (for incremental updates)', null=True),
        ),
    ]
