# Generated by Django 4.2.25 on 2025-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_reviewstatisticsmetadata_max_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstatisticsmetadata',
            name='last_data_loaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when statistics data was last loaded from MediaWiki (not just metadata update)', null=True),
        ),
    ]
