# Generated by Django 4.2.25 on 2025-10-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_merge_20251022_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedrevsstatistics',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaggedrevs_statistics', to='reviews.wiki'),
        ),
    ]
