# Generated by Django 4.2.25 on 2025-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_add_last_data_loaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatisticsmetadata',
            name='last_data_loaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when statistics data was last loaded from MediaWiki', null=True),
        ),
    ]
