# Generated by Django 4.2.25 on 2025-10-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_flaggedrevsstatistics_wiki'),
        ('reviews', '0016_alter_reviewstatisticsmetadata_last_data_loaded_at'),
    ]

    operations = [
    ]
