# Generated by Django 4.2.25 on 2025-10-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_merge_20251027_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewactivity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewactivity',
            name='wiki',
        ),
        migrations.AlterUniqueTogether(
            name='reviewstatisticscache',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewstatisticscache',
            name='wiki',
        ),
        migrations.RemoveField(
            model_name='reviewstatisticsmetadata',
            name='wiki',
        ),
        migrations.DeleteModel(
            name='FlaggedRevsStatistics',
        ),
        migrations.DeleteModel(
            name='ReviewActivity',
        ),
        migrations.DeleteModel(
            name='ReviewStatisticsCache',
        ),
        migrations.DeleteModel(
            name='ReviewStatisticsMetadata',
        ),
    ]
